#!/usr/bin/env bash
set -u

dir=$(cd "$(dirname $0)" && pwd)
files=(
  gitconfig
  gitignore_global
  tmux.conf
  vimrc
  zpreztorc
  zsh*
)

for f in "${files[@]}"; do
  src=$dir/$f
  dst=$HOME/.$f

  # skip if already exists
  [[ -f "$dst" ]] && continue

  ln -s "$src" "$dst"
  echo "Created symlink '$src' => '$dst'"
done
