#!/usr/bin/env bash -u

DIR="$(cd "$(dirname $0)" && pwd)/dotfiles"

for file in `ls "$DIR"`; do
  DEST="$HOME/.$file"

  # skip if already exists
  [[ -f "$DEST" ]] && continue

  ln -s "$DIR/$file" "$DEST"
done
