#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Example aliases
alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder


#===== User configuration =====

# Environmental Variables
export ZSH_HOME=$HOME/.zsh
export MANPATH=/usr/local/man:$MANPATH
export JAVA_HOME=$(/usr/libexec/java_home)
export ANDROID_HOME=/usr/local/Cellar/android-sdk/23.0.2
export GOPATH=$HOME
export LESS=-qRn
export VISUAL=vim
export EDITOR=$VISUAL
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
# enable Japanese input via SSH to set the following environmental variables
# (参考: http://qiita.com/suin/items/629372fd08ee9e9cf727)
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# PATH
# set /usr/local/bin before /usr/bin
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/.pyenv/shims:$PATH
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH=$HOME/.nodebrew/current/bin:$PATH
export PATH=$HOME/.ssh/sh:$PATH
export PATH=$GOPATH/bin:$PATH

# location to save command histories
export HISTFILE=${HOME}/.zsh_history
# number of histories saved in memory
export HISTSIZE=1000
# number of histories saved in file
export SAVEHIST=100000
# ignore duplicate command
setopt hist_ignore_dups
# share history between screens
setopt share_history
# save the start and end
setopt EXTENDED_HISTORY
# remove old command if added one is same
setopt hist_ignore_all_dups
# remove command that starts with space from history
setopt hist_ignore_space
# don't execute the line directly
setopt hist_verify
# remove unnecessary whitespaces
setopt hist_reduce_blanks
# ignore commands already saved in history
setopt hist_save_no_dups
# don't save history command itself
# historyコマンドは履歴に登録しない
setopt hist_no_store
# expand history automatically at completion
setopt hist_expand
# enable completion
autoload -U compinit
compinit
# Disable start/stop control
stty -ixon
# remove duplicate entries in PATH
typeset -U path PATH


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Start screen
#[[ $TERM != "screen" ]] && exec screen

# tmux
[[ "$TMUX" = "" ]] && exec tmux

#==============================
#  Aliases
#==============================
alias vi='vim'
alias lt='ls -t'
alias rm='rm -i'
alias cp='cp -i'

# Git
alias git='hub'
alias gf='git fetch && git diff HEAD..FETCH_HEAD'
alias gmf='git merge FETCH_HEAD --ff'
alias gs='git status'
alias gp='git push'
alias gc='git commit -s'
alias gco='git checkout'
alias gm='git merge'
alias gb='git branch'
alias gr='git reset'
alias gsh='git stash'
alias gsp='git stash pop'
alias gam='git commit --amend'


#==============================
#  cdr
#==============================
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-max 5000
zstyle ':chpwd:*' recent-dirs-default yes
zstyle ':completion:*' recent-dirs-insert both

#==============================
#  zaw
#==============================
if [[ -s "${HOME}/.zsh/zaw/zaw.zsh" ]]; then
  source "${HOME}/.zsh/zaw/zaw.zsh"
fi
# enable case-insensitive
zstyle ':filter-select' case-insensitive yes
bindkey '^@' zaw
bindkey '^r' zaw-history
bindkey '^s' zaw-cdr
#bindkey '^o' zaw-open-file
bindkey '^j' zaw-applications
bindkey '^g' zaw-git-branches
bindkey '^o' zaw-git-status
bindkey '^z' zaw-git-files

#==============================
#  Docker
#==============================
if command -v docker-machine > /dev/null; then
  # fetch the first running machine name
  local default_machine=dev
  local machine=$(docker-machine ls | grep Running | grep $default_machine | head -n 1 | awk '{ print $1 }')
  if [ "$machine" != "" ]; then
    eval "$(docker-machine env $machine)"
    export DOCKER_IP=$(docker-machine ip $machine)
  fi
fi

#==============================
#  Gradle
#==============================
# Always run as daemon
export GRADLE_OPTS='-Dorg.gradle.daemon=true'

#==============================
#  zsh-notify
#==============================
# disable below because incompatible with Yosemite
#source ~/.zsh/zsh-notify/notify.plugin.zsh
#export SYS_NOTIFIER="/usr/local/bin/terminal-notifier"
#export NOTIFY_COMMAND_COMPLETE_TIMEOUT=10

#==============================
#  rbenv
#==============================
# Load rbenv automatically
if command -v rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

#==============================
#  pyenv
#==============================
# Load pyenv automatically
if command -v pyenv > /dev/null; then
  eval "$(pyenv init -)"
fi

#==============================
#  direnv
#==============================
if command -v direnv > /dev/null; then
  eval "$(direnv hook zsh)"
fi

#==============================
#  autojump
#==============================
[[ -s $(brew --prefix)/etc/autojump.sh ]] && . $(brew --prefix)/etc/autojump.sh

#============================================================
#  Incremental completion on zsh
#  (http://mimosa-pudica.net/zsh-incremental.html)
#============================================================
if [[ -s "${ZSH_HOME}/incr/incr-0.2.zsh" ]]; then
  #source "${ZSH_HOME}/incr/incr-0.2.zsh"
fi

#==============================
#  fzf
#==============================
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#==============================
#  thefuck
#==============================
eval "$(thefuck --alias)"
